# Generated by Django 3.2.4 on 2021-06-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffeducation",
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образование",
            },
        ),
        migrations.AlterModelOptions(
            name="stafftraining",
            options={
                "verbose_name": "Повышение квалификации",
                "verbose_name_plural": "Повышения квалификации",
            },
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="position",
            new_name="full_position",
        ),
        migrations.AddField(
            model_name="staff",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="staff",
            name="short_position",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StaffScientificWorks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scientific_works",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Научная работа",
                "verbose_name_plural": "Научные работы",
            },
        ),
        migrations.CreateModel(
            name="StaffResearches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researches",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Область научных интересов",
                "verbose_name_plural": "Области научных интересов",
            },
        ),
        migrations.CreateModel(
            name="StaffCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподоваемая дисциплина",
                "verbose_name_plural": "Преподоваемые дисциплины",
            },
        ),
        migrations.CreateModel(
            name="StaffContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="StaffAwards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда",
                "verbose_name_plural": "Награды",
            },
        ),
    ]
