# Generated by Django 3.2.6 on 2021-08-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "verbose_name": "Преподователь",
                "verbose_name_plural": "Преподователи",
            },
        ),
    ]
