# Generated by Django 3.2.6 on 2021-08-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyen',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='vacancykg',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='vacancyru',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.DeleteModel(
            name='VacancyEN',
        ),
        migrations.DeleteModel(
            name='VacancyKG',
        ),
        migrations.DeleteModel(
            name='VacancyRU',
        ),
    ]
