# Generated by Django 3.2.4 on 2021-06-21 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210621_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('additional_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='staff.additionaldata')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_data', to='staff.staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='staffcontacts',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffcourses',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffeducation',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffresearches',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffscientificworks',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='stafftraining',
            name='staff',
        ),
        migrations.DeleteModel(
            name='StaffAwards',
        ),
        migrations.DeleteModel(
            name='StaffContacts',
        ),
        migrations.DeleteModel(
            name='StaffCourses',
        ),
        migrations.DeleteModel(
            name='StaffEducation',
        ),
        migrations.DeleteModel(
            name='StaffResearches',
        ),
        migrations.DeleteModel(
            name='StaffScientificWorks',
        ),
        migrations.DeleteModel(
            name='StaffTraining',
        ),
    ]
