# Generated by Django 3.2.4 on 2021-06-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210621_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffadditionaldata',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AlterField(
            model_name='staffadditionaldata',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='staff.staff'),
        ),
    ]
