# Generated by Django 3.2.4 on 2021-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_auto_20210621_0631"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
