# Generated by Django 3.2.4 on 2021-06-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_vacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="salary",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
