# Generated by Django 3.2.6 on 2021-08-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20210828_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafftraining',
            old_name='description_kg',
            new_name='description_ky',
        ),
    ]
