# Generated by Django 3.2.6 on 2021-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0011_rename_description_kg_stafftraining_description_ky"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffscientificworkskg",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="staffscientificworksru",
            name="parent",
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="magazin_name",
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="magazin_name_en",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="magazin_name_ky",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="magazin_name_ru",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="title",
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="title_en",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="title_ky",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staffscientificworks",
            name="title_ru",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="stafftraining",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="stafftraining",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="stafftraining",
            name="description_ky",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="stafftraining",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.DeleteModel(
            name="StaffScientificWorksEN",
        ),
        migrations.DeleteModel(
            name="StaffScientificWorksKG",
        ),
        migrations.DeleteModel(
            name="StaffScientificWorksRU",
        ),
    ]
