# Generated by Django 3.2.6 on 2021-08-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staff', '0013_auto_20210828_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffkg',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='staffru',
            name='parent',
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StaffEN',
        ),
        migrations.DeleteModel(
            name='StaffKG',
        ),
        migrations.DeleteModel(
            name='StaffRU',
        ),
    ]
