# Generated by Django 3.2.6 on 2021-08-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0014_auto_20210828_1113"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="full_name_en",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="full_name_ky",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="full_name_ru",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="role_en",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="role_ky",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="role_ru",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
