# Generated by Django 3.2.6 on 2021-08-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20210829_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role_ky',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role_ru',
        ),
    ]
