# Generated by Django 3.2.6 on 2021-08-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0017_auto_20210829_1031"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="role",
            new_name="position",
        ),
    ]
