# Generated by Django 3.2.6 on 2021-08-29 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0018_rename_role_staff_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Год получения")),
                (
                    "description",
                    models.TextField(verbose_name="Информация о награде"),
                ),
                (
                    "description_ru",
                    models.TextField(
                        null=True, verbose_name="Информация о награде"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        null=True, verbose_name="Информация о награде"
                    ),
                ),
                (
                    "description_ky",
                    models.TextField(
                        null=True, verbose_name="Информация о награде"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="staff.staff",
                    ),
                ),
            ],
        ),
    ]
