# Generated by Django 3.2.6 on 2021-08-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_staff_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
