# Generated by Django 3.2.6 on 2021-09-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20210906_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftraining',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='stafftraining',
            name='to_year',
        ),
        migrations.AddField(
            model_name='stafftraining',
            name='date',
            field=models.DateField(default='2003-11-22', verbose_name='До'),
            preserve_default=False,
        ),
    ]
