# Generated by Django 3.2.6 on 2021-09-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_alter_stafftraining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffscientificworks',
            name='release_date',
            field=models.CharField(max_length=512),
        ),
    ]
