# Generated by Django 3.2.6 on 2021-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_alter_staffscientificworks_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffscientificworks',
            name='magazin_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='staffscientificworks',
            name='magazin_name_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='staffscientificworks',
            name='magazin_name_ky',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='staffscientificworks',
            name='magazin_name_ru',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='staffscientificworks',
            name='release_date',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
