# Generated by Django 3.2.6 on 2021-09-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_auto_20210906_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffreward',
            name='year',
        ),
        migrations.AddField(
            model_name='staffreward',
            name='date',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Дата получения'),
        ),
    ]
