# Generated by Django 3.2.6 on 2021-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20210906_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftraining',
            name='date',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Дата'),
        ),
    ]
