# Generated by Django 3.2.6 on 2021-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_alter_stafftraining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffexperience',
            name='overall',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='staffexperience',
            name='pedagogical',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
