# Generated by Django 3.2.6 on 2021-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_auto_20210906_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffexperience',
            name='overall',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='staffexperience',
            name='pedagogical',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
