# Generated by Django 3.2.6 on 2021-09-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_auto_20210906_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcontactemail',
            name='corporate',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffcontactemail',
            name='personal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
