# Generated by Django 3.2.6 on 2021-09-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureau',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='structure_title',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='structure_title_en',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='structure_title_ky',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='structure_title_ru',
        ),
    ]
