# Generated by Django 3.2.6 on 2021-09-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0002_auto_20210908_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи'),
        ),
        migrations.AddField(
            model_name='bureau',
            name='tasks_en',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи'),
        ),
        migrations.AddField(
            model_name='bureau',
            name='tasks_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи'),
        ),
        migrations.AddField(
            model_name='bureau',
            name='tasks_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='activities',
            field=models.TextField(blank=True, null=True, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='activities_en',
            field=models.TextField(blank=True, null=True, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='activities_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='activities_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='goal_en',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='goal_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='goal_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
        migrations.DeleteModel(
            name='BureauTasks',
        ),
    ]
