# Generated by Django 3.2.6 on 2021-09-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0004_auto_20210908_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bureaumember',
            old_name='staff',
            new_name='member',
        ),
    ]
