default_language_version:
  python: "3.9"

repos:
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort