# Generated by Django 3.2.6 on 2021-08-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Картинка мероприятия', 'verbose_name_plural': 'Картинки мероприятия'},
        ),
    ]
