# Generated by Django 3.2.6 on 2021-09-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'Благотворительность', 'verbose_name_plural': 'Благотворительности'},
        ),
    ]
