version: 2.1

jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh
                  -oStrictHostKeyChecking=no
                  -v $SSH_USER@$SSH_HOST
                  PROJECT_ROOT=$PROJECT_ROOT
                  "$PROJECT_ROOT".circleci/deploy.sh

workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master