# Generated by Django 3.2.4 on 2021-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Документ для поступления",
                "verbose_name_plural": "Документы для поступления",
            },
        ),
    ]
