# Generated by Django 3.2.4 on 2021-06-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'verbose_name': 'Документ для поступления', 'verbose_name_plural': 'Документы для поступления'},
        ),
    ]
