# Generated by Django 3.2.6 on 2021-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubkg',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='clubru',
            name='parent',
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='supervisor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='supervisor_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='supervisor_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='supervisor_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ClubEN',
        ),
        migrations.DeleteModel(
            name='ClubKG',
        ),
        migrations.DeleteModel(
            name='ClubRU',
        ),
    ]
