# Generated by Django 3.2.6 on 2021-08-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0017_auto_20210829_1031"),
        ("department", "0004_departmentheadteacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentheadteacher",
            options={"verbose_name": "Заведующий"},
        ),
        migrations.AlterField(
            model_name="departmentheadteacher",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head_teacher",
                to="staff.staff",
                verbose_name="Зав.кафедры",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=255)),
                ("first_email", models.EmailField(max_length=254)),
                ("second_email", models.EmailField(max_length=254)),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="department.department",
                    ),
                ),
            ],
        ),
    ]
