# Generated by Django 3.2.6 on 2021-08-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20210829_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год получения')),
                ('description', models.TextField(verbose_name='Информация о награде')),
                ('description_ru', models.TextField(null=True, verbose_name='Информация о награде')),
                ('description_en', models.TextField(null=True, verbose_name='Информация о награде')),
                ('description_ky', models.TextField(null=True, verbose_name='Информация о награде')),
            ],
        ),
    ]
