# Generated by Django 3.2.6 on 2021-08-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0010_departmentreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentreward",
            name="department",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewards",
                to="department.department",
            ),
            preserve_default=False,
        ),
    ]
