# Generated by Django 3.2.6 on 2021-09-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0014_auto_20210906_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcontacts',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес'),
        ),
    ]
