# Generated by Django 3.2.6 on 2021-09-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0015_departmentcontacts_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='pps_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о ППС'),
        ),
        migrations.AddField(
            model_name='department',
            name='pps_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о ППС'),
        ),
        migrations.AddField(
            model_name='department',
            name='pps_info_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о ППС'),
        ),
        migrations.AddField(
            model_name='department',
            name='pps_info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о ППС'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pps_number',
            field=models.TextField(blank=True, null=True, verbose_name='Количество преподователей'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pps_number_en',
            field=models.TextField(blank=True, null=True, verbose_name='Количество преподователей'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pps_number_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Количество преподователей'),
        ),
        migrations.AlterField(
            model_name='department',
            name='pps_number_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Количество преподователей'),
        ),
    ]
