# Generated by Django 3.2.6 on 2021-09-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_auto_20210906_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='foundation_year',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Год образования'),
        ),
    ]
