# Generated by Django 3.2.6 on 2021-09-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('title', models.CharField(max_length=512)),
                ('title_ru', models.CharField(max_length=512, null=True)),
                ('title_en', models.CharField(max_length=512, null=True)),
                ('title_ky', models.CharField(max_length=512, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='InternationalEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('InternationalEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='international_event.internationalevent')),
            ],
            options={
                'verbose_name': 'Картинка мероприятия',
                'verbose_name_plural': 'Картинки мероприятия',
            },
        ),
    ]
