# Generated by Django 3.2.4 on 2021-06-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kgua_life", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
    ]
