# Generated by Django 3.2.4 on 2021-06-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kgua_life", "0002_alter_event_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Благотворительность",
                "verbose_name_plural": "Благотворительность",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
    ]
