# Generated by Django 3.2.6 on 2021-08-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kgua_life", "0004_club_jubilee_mug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Club",
        ),
    ]
