# Generated by Django 3.1.7 on 2021-03-28 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "ru"), ("en", "en"), ("kg", "kg")],
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
