# Generated by Django 3.1.7 on 2021-04-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.ImageField(default=1, upload_to="profile/pictures/"),
            preserve_default=False,
        ),
    ]
