# Generated by Django 3.1.7 on 2021-04-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_auto_20210403_0659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="locale",
            field=models.CharField(
                blank=True,
                choices=[("ru", "ru"), ("en", "en"), ("kg", "kg")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile/pictures/"
            ),
        ),
    ]
