# Generated by Django 3.1.7 on 2021-04-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0006_sharedaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedaction",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="sharedaction",
            name="to_user",
        ),
        migrations.AddField(
            model_name="sharedaction",
            name="performer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_actions_as_performer",
                to="authorization.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sharedaction",
            name="target",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_actions_as_target",
                to="authorization.user",
            ),
            preserve_default=False,
        ),
    ]
