# Generated by Django 3.2.1 on 2021-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0010_auto_20210506_0411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("update", "update"),
                    ("ebay_buy", "ebay_buy"),
                    ("ebay_sell", "ebay_sell"),
                ],
                max_length=255,
            ),
        ),
    ]
